### ISSUE TITLE
Aggiungere opzione di default "Selezionare opzione" nelle select

### ISSUE THREAD

**Issue by filippo-mancinelli** [FREEDuu/QuestPlatform#4]
Nelle select spesso capita che la risposta corretta sia già selezionata...
![image](https://github.com/FREEDuu/QuestPlatform/assets/73702913/a32f6aec-f03f-4f49-9105-392498c48aac)

Invece dovrebbe essere così:
![image](https://github.com/FREEDuu/QuestPlatform/assets/73702913/eee5479a-ff40-4ea7-8b98-b8f758193170)

@FREEDuu gay

**Comment by FREEDuu** [comment]
non basta mettere un valore di default sul form ? dici va messe dopo nella generazione delle varianti?

**Comment by filippo-mancinelli** [comment]
fatto >:(

```python
print('fatto')
```
