### ISSUE TITLE
Errore login utente senza statistica

### ISSUE THREAD

**Issue by filippo-mancinelli** [FREEDuu/QuestPlatform#5]
Quando si fa la login con un utente che non ha nessun record nella tabella statistiche appare questo errore:

![image](https://github.com/FREEDuu/QuestPlatform/assets/73702913/5b9476a0-be52-467e-9909-ac99c4dd55ab)

nel file page_views.py:
![image](https://github.com/FREEDuu/QuestPlatform/assets/73702913/2ddbafe0-122c-4d24-b935-f6cc187569c9)

**Comment by FREEDuu** [comment]
chissà perchè... (è sempre per il fatto che devi creare le statistiche quando crei un utente (le stelle stanno nelle statistiche)) [GAYmer]

**Comment by FREEDuu** [comment]
risolta
