### ISSUE TITLE
ValueError sulla pagina statistiche

### ISSUE THREAD

**Issue by filippo-mancinelli** [FREEDuu/QuestPlatform#6]
Errore quando si accede alla pagina statistiche con un nuovo utente appena creato, forse ancora a causa di mancanza dati nella tabella statistiche per l'utente

![image](https://github.com/FREEDuu/QuestPlatform/assets/73702913/8239144d-5459-4a9a-bdec-ac40732eeb8e)

**Comment by FREEDuu** [comment]
te lo avevo anche detto che bisogna creare anche le statistiche quando si crea un nuovo utente GAYmer

**Comment by filippo-mancinelli** [comment]
😭

**Comment by FREEDuu** [comment]
risolta
